version: '2'
services:
  spark-worker-1:
    image: bde2020/spark-worker:2.3.2-hadoop2.7
    environment:
      SPARK_MASTER: spark://spark-master:7077
    ports:
    - 8081:8081/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: spark-worker=true
  spark-master:
    image: bde2020/spark-master:2.3.2-hadoop2.7
    environment:
      INIT_DAEMON_STEP: setup_spark
    ports:
    - 8080:8080/tcp
    - 7077:7077/tcp
