version: '2'
services:
  datanode:
    image: uhopper/hadoop-datanode
    environment:
      CLUSTER_NAME: hadoop
      CORE_CONF_fs_defaultFS: hdfs://10.132.144.39:8020
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: 'false'
    stdin_open: true
    network_mode: host
    volumes:
    - /data/hadoop/datanode:/hadoop/dfs/data
    tty: true
    links:
    - namenode:namenode
    ports:
    - 50010:50010/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: hadoop-datanode=true
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: hadoop-datanode=true
      hadoop-datanode: 'true'
  namenode:
    image: uhopper/hadoop-namenode
    hostname: namenode
    environment:
      CLUSTER_NAME: hadoop
      CORE_CONF_fs_defaultFS: hdfs://10.132.144.39:8020
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: 'false'
    stdin_open: true
    network_mode: host
    volumes:
    - /data/hadoop/namenode:/hadoop/dfs/name
    tty: true
    ports:
    - 50070:50070/tcp
    - 8020:8020/tcp
    labels:
      hadoop-namenode: 'true'
      io.rancher.scheduler.affinity:host_label: hadoop-namenode=true
      io.rancher.container.pull_image: always