version: "2"
services:
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9092
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
    stdin_open: true
    external_links:
      - zookeeper/zoo2:zoo2
      - zookeeper/zoo3:zoo3
      - zookeeper/zoo1:zoo1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    ports:
      - 9092:9092/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: kafka=true
